name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test      
    - name: Push to ECR
      run: |
          docker login --username AWS --password ${{secrets.AWS_SECRET_ACCESS_KEY}} ${{secrets.AWS_INSTANCE}} &&
          docker build -t ambassador $GITHUB_WORKSPACE && wait $!
          docker tag ambassador:latest ${{secrets.AWS_INSTANCE}}/ambassador:latest && wait $!
          docker push ${{secrets.AWS_INSTANCE}}/ambassador:latest && wait $!
#     - name: Configure SSH
#       run: |
#           mkdir -p ~/.ssh/
#           echo "$SSH_KEY" > ~/.ssh/staging.key
#           chmod 600 ~/.ssh/staging.key
#           cat >>~/.ssh/config <<END
#           Host staging
#             HostName $SSH_HOST
#             User $SSH_USER
#             IdentityFile ~/.ssh/staging.key
#             StrictHostKeyChecking no
#           END
#       env:
#           SSH_USER: ${{ secrets.STAGING_SSH_USER }}
#           SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
#           SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
    - name: Execute SSH commmands on remote server
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: ${{ secrets.STAGING_SSH_HOST }}
        privateKey: ${{ secrets.STAGING_SSH_KEY }}
        command: sudo ./deploy.sh
