name: Clojure CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test      
    - name: Push to ECR
      run: |
          docker login --username AWS --password ${{secrets.AWS_SECRET_ACCESS_KEY}} ${{secrets.AWS_INSTANCE}} &
          docker build -t ambassador $GITHUB_WORKSPACE & wait $!
          docker tag ambassador:latest ${{secrets.AWS_INSTANCE}}/ambassador:latest & wait $!
          docker push ${{secrets.AWS_INSTANCE}}/ambassador:latest & wait $!
    - name: Deploy new version
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: echo ${{secrets.GH_USER_PASSWORD}} | sudo -S ./build.sh
        host: ${{ secrets.STAGING_SSH_HOST }}
        username: github
        privateKey: ${{ secrets.STAGING_SSH_KEY}}
