name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test      
    - name: Push to ECR
      run: |
          docker login --username AWS --password ${{secrets.AWS_SECRET_ACCESS_KEY}} ${{secrets.AWS_INSTANCE}} &&
          docker build -t ambassador $GITHUB_WORKSPACE && wait $!
          docker tag ambassador:latest ${{secrets.AWS_INSTANCE}}/ambassador:latest && wait $!
          docker push ${{secrets.AWS_INSTANCE}}/ambassador:latest && wait $!
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_SSH_HOST }}
        username: ${{ secrets.STAGING_SSH_USER }}
        key: ${{ secrets.STAGING_SSH_KEY }}
        script: whoami
